<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Xunit.StaFact" Version="4.0.24" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\shared\Em.Ui.Wpf.Core\Em.Ui.Wpf.Core.csproj" />
    </ItemGroup>

</Project>
