-- Upgrade EMPTY single-feed installations only. No feed is seeded, no data is reset.
-- Stop the old host, inspect legacy store artifacts, and back up the core database + store first.
SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF OBJECT_ID('dbo.ta_NuPakPrefix','U') IS NULL
 THROW 51000,'NuPak is not installed: use tables/040-nupak.sql for a new installation.',1;
IF COL_LENGTH('dbo.ta_NuPakPrefix','cNuPakFeedId') IS NULL
BEGIN
 IF EXISTS(SELECT 1 FROM dbo.ta_NuPakPrefix) OR EXISTS(SELECT 1 FROM dbo.ta_NuPakPackage)
 OR EXISTS(SELECT 1 FROM dbo.ta_NuPakVersion) OR EXISTS(SELECT 1 FROM dbo.ta_NuPakPrefixRobot)
  THROW 51000,'Populated legacy NuPak cannot be upgraded automatically. Determine destination feeds explicitly; nothing was changed.',1;
IF OBJECT_ID('dbo.ta_NuPakFeed','U') IS NULL
BEGIN
 CREATE TABLE dbo.ta_NuPakFeed(
 cNuPakFeedId char(26) NOT NULL PRIMARY KEY,
 cNuPakFeedSlug varchar(64) COLLATE Latin1_General_100_CI_AS NOT NULL,
 cNuPakFeedName varchar(100) NOT NULL,
 cNuPakFeedDescription varchar(500) NULL,
 cNuPakFeedEnabled bit NOT NULL,
 cNuPakFeedAnonymousRead bit NOT NULL,
 ustamp datetime NOT NULL,datestamp datetime NOT NULL,json_object nvarchar(max) NULL,
 CONSTRAINT UQ_NuPakFeedSlug UNIQUE(cNuPakFeedSlug));
END;
EXEC(N'CREATE OR ALTER VIEW dbo.vi_NuPakFeed AS SELECT * FROM dbo.ta_NuPakFeed');

 ALTER TABLE dbo.ta_NuPakPrefix ADD cNuPakFeedId char(26) NOT NULL;
 ALTER TABLE dbo.ta_NuPakPackage ADD cNuPakFeedId char(26) NOT NULL;
 ALTER TABLE dbo.ta_NuPakAudit ADD cNuPakFeedId char(26) NULL,cNuPakAuditFeedSlug varchar(64) NULL,cNuPakAuditFeedName varchar(100) NULL;
 ALTER TABLE dbo.ta_NuPakPrefix DROP CONSTRAINT UQ_NuPakPrefix;
 ALTER TABLE dbo.ta_NuPakPackage DROP CONSTRAINT UQ_NuPakPackage;
 -- Original FK names were generated by SQL Server. Drop only the package-to-prefix FK.
 DECLARE @drop nvarchar(max)=N'';
 SELECT @drop=@drop+N'ALTER TABLE dbo.ta_NuPakPackage DROP CONSTRAINT '+QUOTENAME(name)+N';'
 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID('dbo.ta_NuPakPackage') AND referenced_object_id=OBJECT_ID('dbo.ta_NuPakPrefix');
 EXEC sp_executesql @drop;
 EXEC(N'ALTER TABLE dbo.ta_NuPakPrefix ADD CONSTRAINT UQ_NuPakPrefix UNIQUE(cNuPakFeedId,cNuPakPrefixName), CONSTRAINT UQ_NuPakPrefixFeedId UNIQUE(cNuPakFeedId,cNuPakPrefixId), CONSTRAINT FK_NuPakPrefixFeed FOREIGN KEY(cNuPakFeedId) REFERENCES dbo.ta_NuPakFeed(cNuPakFeedId);
 ALTER TABLE dbo.ta_NuPakPackage ADD CONSTRAINT UQ_NuPakPackage UNIQUE(cNuPakFeedId,cNuPakPackageName), CONSTRAINT FK_NuPakPackageFeed FOREIGN KEY(cNuPakFeedId) REFERENCES dbo.ta_NuPakFeed(cNuPakFeedId), CONSTRAINT FK_NuPakPackagePrefixFeed FOREIGN KEY(cNuPakFeedId,cNuPakPrefixId) REFERENCES dbo.ta_NuPakPrefix(cNuPakFeedId,cNuPakPrefixId);
 ALTER TABLE dbo.ta_NuPakAudit ADD CONSTRAINT FK_NuPakAuditFeed FOREIGN KEY(cNuPakFeedId) REFERENCES dbo.ta_NuPakFeed(cNuPakFeedId);
 UPDATE dbo.ta_NuPakAudit SET cNuPakAuditFeedName=''Legacy single-feed history'';');
END;
EXEC(N'CREATE OR ALTER VIEW dbo.vi_NuPakFeed AS SELECT * FROM dbo.ta_NuPakFeed');
EXEC(N'CREATE OR ALTER VIEW dbo.vi_NuPakPrefix AS SELECT t.cNuPakFeedId,t.cNuPakPrefixId,t.cNuPakPrefixName,t.cNuPakPrefixState,t.cNuPakPrefixDescription,t.ustamp,t.datestamp,t.json_object FROM dbo.ta_NuPakPrefix t');
EXEC(N'CREATE OR ALTER VIEW dbo.vi_NuPakPackage AS SELECT t.cNuPakFeedId,t.cNuPakPackageId,t.cNuPakPrefixId,t.cNuPakPackageName,t.cNuPakPackageState,t.ustamp,t.datestamp,t.json_object,p.cNuPakPrefixName FROM dbo.ta_NuPakPackage t JOIN dbo.ta_NuPakPrefix p ON p.cNuPakPrefixId=t.cNuPakPrefixId');
EXEC(N'CREATE OR ALTER VIEW dbo.vi_NuPakVersion AS SELECT t.cNuPakVersionId,t.cNuPakPackageId,t.cNuPakVersionNumber,t.cNuPakVersionOriginal,t.cNuPakVersionPrerelease,t.cNuPakVersionState,t.cNuPakVersionRecycledAt,t.cNuPakVersionSize,t.cNuPakVersionHash,t.cNuPakVersionTitle,t.cNuPakVersionDescription,t.cNuPakVersionAuthors,t.cNuPakVersionTags,t.cNuPakVersionPushedBy_cRobotId,t.ustamp,t.datestamp,t.json_object FROM dbo.ta_NuPakVersion t');
EXEC(N'CREATE OR ALTER VIEW dbo.vi_NuPakAudit AS SELECT t.cNuPakFeedId,t.cNuPakAuditFeedSlug,t.cNuPakAuditFeedName,t.cNuPakAuditId,t.cNuPakAuditAt,t.cNuPakAuditAction,t.cNuPakAuditPackage,t.cNuPakAuditVersion,t.cNuPakAuditActorKind,t.cNuPakAuditActorId,t.cNuPakAuditActorName,t.cNuPakAuditResult,t.cNuPakAuditDetail,t.cNuPakAuditAddress,t.ustamp,t.datestamp,t.json_object FROM dbo.ta_NuPakAudit t');
EXEC(N'IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=''IX_NuPakAuditFeedAt'' AND object_id=OBJECT_ID(''dbo.ta_NuPakAudit''))
 CREATE INDEX IX_NuPakAuditFeedAt ON dbo.ta_NuPakAudit(cNuPakFeedId,cNuPakAuditAt DESC);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=''IX_NuPakVersionRecycle'' AND object_id=OBJECT_ID(''dbo.ta_NuPakVersion''))
 CREATE INDEX IX_NuPakVersionRecycle ON dbo.ta_NuPakVersion(cNuPakVersionState,cNuPakVersionRecycledAt,cNuPakPackageId) INCLUDE(cNuPakVersionSize);
IF NOT EXISTS(SELECT 1 FROM dbo.ta_Meta WHERE cMetaKey=''NuPakSchemaVersion'')
 INSERT dbo.ta_Meta(cMetaKey,cMetaValue,cMetaDescription,ustamp) VALUES(''NuPakSchemaVersion'',''2'',''NuPak multi-feed schema'',GETUTCDATE());
ELSE UPDATE dbo.ta_Meta SET cMetaValue=''2'',ustamp=GETUTCDATE() WHERE cMetaKey=''NuPakSchemaVersion'';
');
COMMIT;
