using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Em.Api.Core.Models
{
   /// <summary>
   /// One step within a request: who must decide, what the decision is, and where its signature is drawn
   /// on the PDF.
   /// </summary>
   /// <remarks>
   /// All steps are created at once when the request is submitted, including those whose turn has not
   /// come, so the flow is visible in full from the start and does not change midway.
   /// </remarks>
   [Table("ta_ApprovalRequestStep")]
   public class ta_ApprovalRequestStep
   {
      /// <summary>Primary key (ULID).</summary>
      [Key]
      public string cApprovalRequestStepId { get; set; } = string.Empty;

      /// <summary>Key of the related <c>ta_ApprovalRequest</c> row.</summary>
      public string cApprovalRequestId { get; set; } = string.Empty;

      /// <summary>
      /// Step name, as declared by the module. This name is also the name of the claim required to decide
      /// it.
      /// </summary>
      public string cApprovalRequestStepName { get; set; } = string.Empty;

      /// <summary>Claim that must be held to decide this step.</summary>
      public string cApprovalRequestStepClaim { get; set; } = string.Empty;

      /// <summary>
      /// Level this step belongs to. Several steps can share a level, and all of them must be approved
      /// before the next level starts.
      /// </summary>
      public int cApprovalRequestStepLevel { get; set; }

      /// <summary>Order of this step within its level, for a stable display.</summary>
      public int cApprovalRequestStepOrder { get; set; }

      /// <summary>State of this step.</summary>
      public ApprovalStepStatus cApprovalRequestStepStage { get; set; }

      /// <summary>Who signed, or empty if not decided yet.</summary>
      public string? cApprovalRequestStepSignerId { get; set; }

      /// <summary>When it was signed.</summary>
      public DateTime? cApprovalRequestStepSignedDate { get; set; }

      /// <summary>On what basis the signature is valid: the assigned signer, a substitute, or an override.</summary>
      public ApprovalSignerRole cApprovalRequestStepSignerRole { get; set; }

      /// <summary>
      /// Primary signer represented, when this step was signed by a substitute or an override. Empty for
      /// steps whose signers are not assigned per person - in that case the step name is printed on the
      /// signature.
      /// </summary>
      public string? cApprovalRequestStepOnBehalfId { get; set; }

      /// <summary>
      /// Reason for the decision. May be empty when approving, but required when rejecting, when signing as
      /// a substitute, and when overriding a block.
      /// </summary>
      public string? cApprovalRequestStepNote { get; set; }

      /// <summary>
      /// Verification code of this signature, generated by the engine when the step is decided. Printed on
      /// the signature and on the margin of every PDF page.
      /// </summary>
      public string? cApprovalRequestStepVerificationCode { get; set; }

      /// <summary>
      /// Block reason in effect when the decision was taken, kept as an audit trail. Filled only when the
      /// step was actually blocked and the decision overrode it.
      /// </summary>
      public string? cApprovalRequestStepGuardReason { get; set; }

      /// <summary>Last update time.</summary>
      public DateTime ustamp { get; set; }

      /// <summary>Creation time.</summary>
      public DateTime datestamp { get; set; }

      /// <summary>
      /// Copy of this step's signature and input positions, frozen at submission, plus the input given by
      /// the signer. Frozen so document layout changes only apply to requests submitted afterwards.
      /// </summary>
      public string? json_object { get; set; }
   }
}
